feature/1/회원가입-로그인-로그아웃 구현
BangChef-Project/bangchef-dev pull request #2
Opened 2024-12-06 08:40 UTC by Hanjarang

## 추가 사항
- 회원가입과 로그인, 로그아웃 구현을 위한 Entity / Repository / Service / DTO / Controller 생성
- 오류를 담당하는 Entity / Exception ( GlobalExceptionHandler / ErrorResponse / ErrorCode / CustomException) 생성
- SecurityConfig 생성
- jjwt 패키지 하위에 토큰 발급을 위한 JWTUtil , JWTFilter / 로그인-로그아웃 필터 생성
- token을 담당하는 Entity / Repository / Service / Controller

## 변경 사항
- 없음.

## 이유
- 없음.

## 테스트 방법
1. Postman을 통해 회원가입되는 것을 확인
2. Postman을 통해 로그인시 access token 이 발급되는 것을 확인
3. h2-console 을 통해 refresh token 발급된 것을 확인
4. Postman을 통해 로그아웃 되는 것을 확인

## API 테스트 결과 

- 회원가입
<img width="744" alt="회원가입" src="https://github.com/user-attachments/assets/15eabb88-157f-4d44-a5ab-f2363ce99936">

- 로그인
<img width="744" alt="로그인" src="https://github.com/user-attachments/assets/03d3fb24-94cc-4773-ad9b-68c6d2185000">

- refresh token 발급 확인
<img width="1150" alt="리프레쉬 토큰" src="https://github.com/user-attachments/assets/01d543cf-e131-43e2-8725-e17846e3f821">

- 로그아웃
<img width="744" alt="로그아웃" src="https://github.com/user-attachments/assets/72163c4c-0f34-448b-9390-729c8962777a">

close #1

2024-12-07 05:08 UTC, wooco96 requested changes
리뷰 보시고 수정할 거 있으면 수정해주시면 감사하겠습니다!

2024-12-07 05:08 UTC, wooco96 commented on src/main/java/com/bangchef/recipe_platform/user/entity/User.java
> +@Table(name = "users")
클래스명과 테이블명이 같으니 삭제하셔도 괜찮을 것 같습니다!

2024-12-07 05:08 UTC, wooco96 commented on src/main/java/com/bangchef/recipe_platform/user/entity/Role.java
> +    USER, ADMIN
ROLE_ADMIN, ROLE_CHEF, ROLE_USER 로 해주시면 좋을 거 같고 common/enums 패키지 추가하셔서 옮겨주시면 좋을 거 같습니다!

2024-12-07 05:08 UTC, wooco96 commented on src/main/java/com/bangchef/recipe_platform/user/dto/LoginDto.java
> +    private String username;
로그인할 때 이메일로 받을 거구 username은 닉네임입니다!

2024-12-07 05:08 UTC, wooco96 commented on src/main/java/com/bangchef/recipe_platform/user/service/JoinService.java
> +            throw new RuntimeException("이미 등록된 아이디입니다.");
회원가입시 이메일인증을 통한 이메일, 비밀번호, 닉네임만 받을 거구 닉네임은 중복이 불가하니 "이미 존재하는 닉네임입니다."로 수정해주시면 좋을 거 같습니다!

2024-12-07 05:08 UTC, wooco96 commented on src/main/java/com/bangchef/recipe_platform/RecipePlatformApplication.java
> +import org.springframework.context.annotation.ComponentScan;
혹시 import한 이유가 있을까요? SpringBootApplication에 포함되어 있어서 따로 선언 안 해도 되지 않나용?!

2024-12-08 14:03 UTC, Hanjarang commented on src/main/java/com/bangchef/recipe_platform/RecipePlatformApplication.java
> +import org.springframework.context.annotation.ComponentScan;
삭제했습니다

2024-12-08 14:03 UTC, Hanjarang commented on src/main/java/com/bangchef/recipe_platform/user/service/JoinService.java
> +            throw new RuntimeException("이미 등록된 아이디입니다.");
수정했습니다.

2024-12-08 14:04 UTC, Hanjarang commented on src/main/java/com/bangchef/recipe_platform/user/dto/LoginDto.java
> +    private String username;
로그인시 이메일로 입력받도록 수정했습니다.

2024-12-08 14:04 UTC, Hanjarang commented on src/main/java/com/bangchef/recipe_platform/user/entity/Role.java
> +    USER, ADMIN
추가하고 패키지 위치 수정했습니다

2024-12-08 14:04 UTC, Hanjarang commented on src/main/java/com/bangchef/recipe_platform/user/entity/User.java
> +@Table(name = "users")
삭제했습니다.

2024-12-09 05:17 UTC, wooco96 approved these changes
확인했습니다.

2024-12-09 05:18 UTC, wooco96 approved these changes
확인했습니다.

2024-12-09 05:19 UTC, merged