유저검색-레시피검색 구현
BangChef-Project/bangchef-dev pull request #8
Opened 2024-12-15 16:45 UTC by 0xc0de1dea

> ### 🔨 변경사항
> - Fix: 유저 Entity에 subscribers, avgRating 추가
> - Feat: 유저 이름으로 검색하는 기능 추가 ( 정렬 방식은 가나다순, 구독자순, 별점순 )
> - Feat: 레시피 타이틀로 검색하는 기능 추가 ( 정렬 방식은 조회수순, 평점순, 즐겨찾기순 )

![image](https://github.com/user-attachments/assets/36b1eddb-447e-4ce5-a9c1-23d0838123cf)
![image](https://github.com/user-attachments/assets/7aa66718-4ab4-4231-9cc1-6acea02e2dc3)
레시피 생성 후,

![image](https://github.com/user-attachments/assets/a97d6a39-2e2b-44d2-aba3-8c8982e47765)
레시피 타이틀로 검색했을 때,

![image](https://github.com/user-attachments/assets/190c4f78-478e-48c4-bd59-18eddc350736)
레시피 카테고리로 검색했을 때

2024-12-16 08:00 UTC, wooco96 requested changes
수정할 건 수정부탁드립니다!

2024-12-16 08:00 UTC, wooco96 commented on src/main/java/com/bangchef/recipe_platform/common/enums/CookCategory.java
이거는 왜 생성하신건가욥?!

2024-12-16 08:00 UTC, wooco96 commented on src/main/java/com/bangchef/recipe_platform/recipe/dto/CategoriesBySortDto.java
요청 객체인지 응답 객체인지 RequestRecipeDto, ResponseRecipeDto 파일에 구분해서 넣어주세욥!

2024-12-16 08:00 UTC, wooco96 commented on src/main/java/com/bangchef/recipe_platform/recipe/entity/Recipe.java
> +    private String description; // git 레시피 설명
요거는 뭔가욥?!

2024-12-16 10:54 UTC, 0xc0de1dea commented on src/main/java/com/bangchef/recipe_platform/common/enums/CookCategory.java
지운다는게 깜박했네용 ㅋㅋ..

2024-12-16 10:55 UTC, 0xc0de1dea commented on src/main/java/com/bangchef/recipe_platform/recipe/dto/CategoriesBySortDto.java
RequestRecipeDto 안에 넣겠습니당

2024-12-16 10:56 UTC, 0xc0de1dea commented on src/main/java/com/bangchef/recipe_platform/recipe/entity/Recipe.java
> +    private String description; // git 레시피 설명
아마 pull 하는 과정에서 바뀐 것 같아요

2024-12-17 07:43 UTC, wooco96 approved these changes
확인했습니다.

2024-12-17 07:43 UTC, merged